influxdb:
        host: "localhost"
        username: "xxx"
        password: "xxx"
        port: 8086
        dbname: "smog"
plotly:
        username: "xxx"
        api_key: "xxx"
        stream_ids: ["xxx"]
        filename: "smog"
sensor:
        port: '/dev/ttyUSB0'
        host: "rpi0"
        name: "sds011"
        location: "50.282197, 18.655145"